import "./globals.css";
import { Inter } from "next/font/google";
import  Provider  from "@/components/Providers";

export const metadata = {
  title: "APP NAME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-full">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
